# Generated by Django 3.0.8 on 2021-07-13 02:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b00f4bed-c669-4ef5-94e7-33cc86e4c8f3'), primary_key=True, serialize=False)),
                ('title_menu', models.CharField(max_length=200)),
                ('menu_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_option', models.CharField(max_length=200)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.Menu')),
            ],
        ),
    ]
