# Generated by Django 3.0.8 on 2021-07-14 06:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.UUIDField(default=uuid.UUID('da54beeb-c468-4f87-bb09-fcc83d48cb69'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menuapp.Menu'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_worker', models.CharField(max_length=200)),
                ('name_worker', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('date_selection', models.DateTimeField(auto_now_add=True)),
                ('option_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.Option')),
            ],
        ),
    ]
